import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
          <button><Link href={"/"}>Шифр Виженера</Link></button>
          <span> </span>
          <button><Link href={"/perestanovki"}>Шифр перестановки</Link></button>
          <span> </span>
          <button><Link href={"/kuznechik"}>Шифр кузнечик</Link></button>
      </header>
        {children}
      </body>
    </html>
  )
}
